server:
  port: 8002

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://62.234.133.202:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimerzone=Asiz/Shanghai
    username: muzi
    password: 123456
  application:
    name: cloud-payment-server
mybatis-plus:
  configuration:  #打印SQL日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: dr  # 全局逻辑删除的实体字段名
      logic-delete-value: 1   # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: id_worker
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      select-strategy: not_empty
      update-strategy: not_empty
      insert-strategy: not_empty
  #      field-strategy: not-empty    #这种方式已经废弃了
  mapper-locations: #mapper映射文件位置
    - mybatis/mapper/*.xml
  type-aliases-package: com.study.cloud.entities  #元数据的包名

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # defaultZone: http://localhost:7001/eureka
      # 集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8002
    # 访问路径可以显示ip地址
    prefer-ip-address: true


